% -------------------------------------------------------------------
%  Generated by MATLAB on 6-May-2021 14:37:14
%  MATLAB version: 9.8.0.1396136 (R2020a) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('step276.mat');

CFL = 1.2;

L = 1;

Lx = 1;

Ly = 1;

Lz = 1;

N = 32;

Nx = 32;

Ny = 32;

Nz = 32;

O = saveVarsMat.O; % <34x34x34 double> too many elements

Re = 100;

U = 1;

dt = 0.01875;

dx = 0.03125;

dy = 0.03125;

dz = 0.03125;

nu = 0.01;

nxp2 = 34;

nyp2 = 34;

nzp2 = 34;

p = saveVarsMat.p; % <34x34x34 double> too many elements

prk1 = saveVarsMat.prk1; % <34x34x34 double> too many elements

prk2 = saveVarsMat.prk2; % <34x34x34 double> too many elements

prk3 = saveVarsMat.prk3; % <34x34x34 double> too many elements

qu0 = saveVarsMat.qu0; % <34x34x34 double> too many elements

qu1 = saveVarsMat.qu1; % <34x34x34 double> too many elements

qu2 = saveVarsMat.qu2; % <34x34x34 double> too many elements

qu3 = saveVarsMat.qu3; % <34x34x34 double> too many elements

qv0 = saveVarsMat.qv0; % <34x34x34 double> too many elements

qv1 = saveVarsMat.qv1; % <34x34x34 double> too many elements

qv2 = saveVarsMat.qv2; % <34x34x34 double> too many elements

qv3 = saveVarsMat.qv3; % <34x34x34 double> too many elements

qw0 = saveVarsMat.qw0; % <34x34x34 double> too many elements

qw1 = saveVarsMat.qw1; % <34x34x34 double> too many elements

qw2 = saveVarsMat.qw2; % <34x34x34 double> too many elements

qw3 = saveVarsMat.qw3; % <34x34x34 double> too many elements

res = 7.4481361746712738E-5;

resu = 7.4481361746712738E-5;

step = 277;

steps = 10000;

t = 5.193749999999973;

tol = 1E-6;

u = saveVarsMat.u; % <34x34x34 double> too many elements

urk1 = saveVarsMat.urk1; % <34x34x34 double> too many elements

urk2 = saveVarsMat.urk2; % <34x34x34 double> too many elements

urk3 = saveVarsMat.urk3; % <34x34x34 double> too many elements

v = saveVarsMat.v; % <34x34x34 double> too many elements

vrk1 = saveVarsMat.vrk1; % <34x34x34 double> too many elements

vrk2 = saveVarsMat.vrk2; % <34x34x34 double> too many elements

vrk3 = saveVarsMat.vrk3; % <34x34x34 double> too many elements

w = saveVarsMat.w; % <34x34x34 double> too many elements

wrk1 = saveVarsMat.wrk1; % <34x34x34 double> too many elements

wrk2 = saveVarsMat.wrk2; % <34x34x34 double> too many elements

wrk3 = saveVarsMat.wrk3; % <34x34x34 double> too many elements

clear saveVarsMat;
